### ISSUE TITLE
`<Foo bar={{baz}}/>` fails

### ISSUE THREAD

**Issue by Turbo87** [rwjblue/ember-angle-bracket-invocation-polyfill#10]
```hbs
<OpenHomeMobile @platform="ios" @goToMobileSite={{action goToMobileSite}}/>
```

resulted in  `Unclosed element 'openHomeMobile' (on line 4).`

Adding a space before the `/>` solved the issue.

**Comment by rwjblue** [comment]
@Turbo87 - What Ember version? Does the same happen for `<div data-blah={{action lol}}/>`?

**Comment by rwjblue** [comment]
Yeah, looks like an issue with glimmer-vm. Transitioning from the mustache state to tag end state seems to require a space...

**Comment by Turbo87** [comment]
This was with `ember-source@3.0.0`

**Comment by rwjblue** [comment]
Ya, but I think it would have the same issue back to 2.10 all the way through current glimmer-vm master. We'll have to fix it over there I think since the error happens before our AST transform has a chance to run...

**Comment by Turbo87** [comment]
yep, that's what I feared. would probably still be good to document it in a "Caveats" section.

**Comment by rwjblue** [comment]
I created https://github.com/glimmerjs/glimmer-vm/issues/829 to track actually fixing.
