### ISSUE TITLE
Errors on helpers with v1.1.0

### ISSUE THREAD

**Issue by knownasilya** [rwjblue/ember-angle-bracket-invocation-polyfill#12]
I get this error:

```
vendor.js:71725 Uncaught TypeError: Cannot read property 'manager' of null
    at RuntimeResolver.runtimeResolver._lookupComponentDefinition (vendor.js:71725)
    at RuntimeResolver.lookupComponentDefinition (vendor.js:40540)
    at CompileTimeLookup.lookupComponentDefinition (vendor.js:38443)
    at refineInlineSyntax (vendor.js:40373)
    at Inlines.compile (vendor.js:19102)
    at vendor.js:18871
    at Compilers.compile (vendor.js:18738)
    at CompilableTemplateImpl.compile (vendor.js:19508)
    at OutletComponentManager.getLayout (vendor.js:37035)
    at Object.evaluate (vendor.js:23286)
```

The component it tries to evaluate is `page-title`, but that addon supports using just `title` which is transformed via AST. See my comment in that project https://github.com/tim-evans/ember-page-title/issues/123#issuecomment-395131883

I'm testing converting it to an explicit `page-title`.

**Comment by knownasilya** [comment]
Converting it to page-title directly still errors, see the error here: https://gloucesterma.mapgeo.alpha1.appgeo.com/dashboard/

**Comment by knownasilya** [comment]
Didn't notice that 1.1.0 was out, trying that now..

**Comment by knownasilya** [comment]
Ah, alpha was already using 1.1 but local was 1.0.2, so the issue is somewhere in the update from 1.0.2 to 1.1.0.

**Comment by rwjblue** [comment]
Can you give me the template that I can use to test?

**Comment by knownasilya** [comment]
@rwjblue here's a repro https://github.com/knownasilya/ab-repro

**Comment by rwjblue** [comment]
Thank you very much for putting together an awesome reproduction, it made tracking things down super easy!

**Comment by lifeart** [comment]
Seen same issue on  "ember-source": "~3.1.0",
![image](https://user-images.githubusercontent.com/1360552/45547185-8dae1980-b828-11e8-9c08-8f32d457fc35.png)

**Comment by rwjblue** [comment]
Can you create a reproduction repo which demonstrates the problem (if so please create a new issue so we can track things down and get it fixed...)

**Comment by rwjblue** [comment]
Great job tracking this down! Seems like we could write a test that emulates the issue you are seeing (so that we can track it down). I’m thinking of essentially a test like [this one](https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill/blob/bdd2fda209c1262971b2f5611cd4403cb98c5bb0/tests/integration/components/angle-bracket-invocation-test.js#L14) but using `{{component ‘does-not-exist’}}` and asserting empty DOM. Would you mind sending a PR with that test?
