### ISSUE TITLE
ember-cli-htmlbars-inline-precompile Caveat

### ISSUE THREAD

**Issue by jherdman** [rwjblue/ember-angle-bracket-invocation-polyfill#18]
I had an integration test I copied from your test suite to debug why my angle bracket component wasn't working:

```javascript

    this.owner.register('template:components/foo-bar', hbs`hi martin!`);

    await render(hbs`<FooBar />`);

    assert.dom().hasText('hi martin!');
```

The resultant HTML was:

```html
<foobar></foobar>
```

I resolved the issue by bumping ember-cli-htmlbars-inline-precompile to ^1.0.3 from ^1.0.0. Perhaps this should be added to the README?

**Comment by rwjblue** [comment]
Yes, we should definitely smooth this over.  I think we can add that to the README, but I also think we should issue a warning if we detect that the older version is being used.

What do you think?
