### ISSUE TITLE
Input helper not found

### ISSUE THREAD

**Issue by jrowlingson** [rwjblue/ember-angle-bracket-invocation-polyfill#35]
Given the following template:

```
// .hbs
<Input class="foo" />
```

I observe that this input helper is successfully rendered in versions `<=v1.1.9`. In `v1.2.0` I am now seeing the following assertion failure message:

```
"Assertion Failed: Could not find component named "input" (no component or template with that name was found)"
```

```
ember -v                                                                                                                                           ✗ master
ember-cli: 3.3.0
node: 10.4.1
os: darwin x64
```

Related https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill/pull/34, https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill/commit/2cc78b95946104baa4d709b5e2f4cd5b44ac6bf8

**Comment by jrowlingson** [comment]
Doh - after re-reading the title here I see the issue. 😅

**Comment by rwjblue** [comment]
Ya, Ember doesn't expose `{{input}}` as a component just yet. Though we should totally push for that in an RFC...
