### ISSUE TITLE
`let` doesn't work

### ISSUE THREAD

**Issue by raghuvaran** [rwjblue/ember-angle-bracket-invocation-polyfill#37]
```
{{#let (component 'ui/timeline') as |Timeline|}}
<Timeline .../>
{{/let}}
```

doesn't yield `Timeline` nor throw any error.
using `with` instead of `let` works fine!

I'm on `"ember-source": "~3.1.2"`

**Comment by rwjblue** [comment]
How are you using `let` (from which addon)? I don't believe it was a builtin feature until v3.2.0.

**Comment by raghuvaran** [comment]
Sorry, I was under assumption that `ember-angle-bracket-invocation-polyfill` addon will also polyfill `let`. After going thru the RFC again, I understood they are different.
