### ISSUE TITLE
"...attributes is an invalid path" in addon template

### ISSUE THREAD

**Issue by chriskrycho** [rwjblue/ember-angle-bracket-invocation-polyfill#39]
If I write this:

```hbs
<input ...attributes />
```

I see this:

```plain
Template Compiler Error (TemplateCompiler) in @olo/ember-principled-forms/components/form-field/template.hbs

Assertion Failed: ...attributes is an invalid path ('@olo/ember-principled-forms/components/form-field/template.hbs' @ L28:C6)
```

Happy to provide full logs, etc. as is helpful.

I'll also see if I can figure out what the absolute minimal reproduction is. The current one I'm testing with is [here](https://github.com/ololabs/principled-forms/blob/v0.2.1/packages/ember-principled-forms/addon/components/form-field/template.hbs).

**Comment by rwjblue** [comment]
Can you double check that this addon is in dependencies of the addon (not devDependencies)?

**Comment by chriskrycho** [comment]
Ah! It’s in `devDependencies`! I didn’t see anything to that effect in the README; would a PR to that effect be helpful?

**Comment by rwjblue** [comment]
closing for now though...
