### ISSUE TITLE
positionalParams don't seem to work

### ISSUE THREAD

**Issue by cottrellio** [rwjblue/ember-angle-bracket-invocation-polyfill#49]
Here's an example `{{#link-to "posts" 3}}3rd Post{{/link-to}}` => `<LinkTo "posts" 3>3rd Post</LinkTo>`

I get the error:
```
Syntax error at line xx col xx: " is not a valid character within attribute names
```

I'm probably just a noob, but how do I go about handling these situations? :D

**Comment by rwjblue** [comment]
Sorry you ran into issues here! Positional params are intentionally not supported in angle bracket invocation...

**Comment by cottrellio** [comment]
Thanks @rwjblue We can close this issue
