### ISSUE TITLE
Expected behavior when attempting to render yielded variable

### ISSUE THREAD

**Issue by samselikoff** [rwjblue/ember-angle-bracket-invocation-polyfill#52]
(possibly related to https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill/issues/17)

I installed this addon to use in our app (w00t!) and our videos stopped playing.

Tracked it down to this snippet:

```hbs
<video>
  {{#each prioritizedSources as |source|}}
    <source src="{{source.url}}" type="video/{{source.format}}">
  {{/each}}
</video>
```

Nothing happened, the sources just didn't render. I guess I understand why.

I'm just curious about the expected behavior here. Is silence/no output correct? Maybe this is a template linting problem rather than a compiler or run-time error one?

**Comment by rwjblue** [comment]
More details in https://github.com/emberjs/ember.js/issues/16826#issuecomment-408504435.

**Comment by rwjblue** [comment]
Given that the linting rule helps mitigate this and that it’s an ember bug, I’m going to close (we can track over in Ember)...
